[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
kodama = "0.3"
csv = "1.3.1"
godot = "0.3.5"
rand = "0.9.2"
regex = "1.11.2"
ndarray = "0.15"
num-traits = "0.2.19"
chardetng = "0.1.17"
encoding_rs = "0.8.35"
